[llm_nodes:children]
wsl2_gpu
cloud_gpu_ready
cloud_gpu_install
cpu_only

[wsl2_gpu]
wsl-host ansible_host=10.8.1.1 ansible_user=rendal

[cloud_gpu_ready]
#gpu-ready-host ansible_host=10.0.0.10 ansible_user=ubuntu

[cloud_gpu_install]
#gpu-empty-host ansible_host=10.0.0.20 ansible_user=ubuntu

[cpu_only]
#cpu-host ansible_host=192.168.56.50 ansible_user=Alexander
